version: "2"

linters:
  default: none
  enable:
    # Core correctness
    - errcheck # Ensure all errors are handled
    - staticcheck # Broad, modern replacement for vet+extras
    - govet # Core Go analyzer
    - ineffassign # Detects ineffectual assignments
    - unused # Finds unused vars, funcs, etc.
    - nilerr # Detect returning nil instead of err
    - errorlint # Ensure proper error wrapping and comparisons

    # Code quality / design
    - revive # Modern replacement for golint; configurable
    - gocritic # Smart heuristics (tuned below)
    - unparam # Detect unused parameters
    - goconst # Suggest constants for repeated strings/numbers
    - gocyclo # Detect excessive complexity
    - prealloc # Suggest slice preallocation
    - containedctx # Detect context misuse
    - noctx # Detect missing context in external calls
    - durationcheck # Catch invalid time.Duration uses

    # Performance & clarity
    - copyloopvar # Classic Go pitfall with loop vars
    - intrange # Warns about range iteration issues
    - perfsprint # Avoid fmt.Sprintf in performance paths
    - makezero # Avoid unnecessary make() of zero-length slices

    # Hygiene / consistency
    - misspell # Spelling
    - whitespace # Trailing and mixed spaces
    - nolintlint # Detect invalid //nolint comments
  settings:
    gocritic:
      disabled-checks:
        - hugeParam # Common false positives
        - ifElseChain # Style too strict for simple cases
      enabled-tags:
        - performance
        - style
    govet:
      enable-all: true
      disable:
        - shadow # Keeps idiomatic err redeclarations
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: indent-error-flow
          disabled: true
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: true
      exported-fields-are-used: false
      local-variables-are-used: false
      generated-is-used: false
  exclusions:
    paths:
      - "third_party"
      - "pb"

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ekisa-team/syn4pse)
  exclusions:
    paths:
      - "third_party"
      - "pb"
